name: 'Set up environment'

description: 'Sets up environment by setting up credentials, installing dependencies and creating a build'

runs:
  using: composite
  steps:
    - uses: myparcelnl/actions/yarn2-install@v3

    - name: 'Build packages'
      shell: bash
      run: |
        yarn nx run-many --target build --output-style stream
