name: 'Set up environment'

description: 'Sets up environment by setting up credentials, installing dependencies and creating a build'

runs:
  using: composite
  steps:
    - uses: myparcelnl/actions/yarn-install@v3
      with:
        node-version: 18

    - name: 'Build packages'
      shell: bash
      run: |
        yarn nx run-many \
          --runner=cloud \
          --target=build \
          --output-style=stream
