name: 'Set up environment'

description: 'Sets up environment by setting up credentials, installing dependencies and creating a build'

inputs:
  token:
    description: 'GitHub token'
    required: true

  reset-nx-cache:
    description: 'Reset Nx cache'
    required: false

runs:
  using: composite
  steps:
    - uses: myparcelnl/actions/setup-git-credentials@v2
      with:
        token: ${{ inputs.token }}

    - uses: myparcelnl/actions/yarn2-install@v2

    - name: 'Cache Nx'
      uses: actions/cache@v3
      with:
        path: node_modules/.cache/nx
        key: ${{ runner.os }}-cache-nx-${{ hashFiles('**/yarn.lock') }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-cache-nx-${{ hashFiles('**/yarn.lock') }}-
          ${{ runner.os }}-cache-nx-

    - name: 'Reset NX cache'
      if: inputs.reset-nx-cache
      shell: bash
      run: |
        yarn nx reset

    - name: 'Build packages'
      shell: bash
      run: |
        yarn build --output-style stream
