name: 'Set up environment'

description: 'Sets up environment by setting up credentials, installing dependencies and creating a build'

inputs:
  token:
    description: 'GitHub token'
    required: true

runs:
  using: composite
  steps:
    - uses: myparcelnl/actions/setup-git-credentials@v2
      with:
        token: ${{ inputs.token }}

    - uses: myparcelnl/actions/yarn2-install@v2

    - uses: myparcelnl/actions/cache-nx@v2
      with:
        lockfile: '**/yarn.lock'

    - name: 'Build packages'
      shell: bash
      run: |
        yarn build --output-style stream
