# Updated to fix Nx postinstall in CI
checksumBehavior: ignore

compressionLevel: 0

enableGlobalCache: true

enableHardenedMode: false

enableScripts: true

ignorePath: true

nodeLinker: node-modules

npmRegistries:
  //registry.npmjs.org/:
    npmAuthToken: "${NPM_TOKEN:-invalid}"
