checksumBehavior: ignore

compressionLevel: 0

enableGlobalCache: false

nodeLinker: node-modules

npmRegistries:
  //registry.npmjs.org/:
    npmAuthToken: "${NPM_TOKEN:-invalid}"

yarnPath: .yarn/releases/yarn-4.3.1.cjs
