checksumBehavior: ignore

compressionLevel: 0

enableGlobalCache: true

enableScripts: true

ignorePath: true

nodeLinker: node-modules

npmRegistries:
  //registry.npmjs.org/:
    npmAuthToken: "${NPM_TOKEN:-invalid}"
