name: '🔸 Run tests 🧪'

on:
  workflow_call:

jobs:
  test:
    name: 'Run unit tests'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}

      - name: 'Run tests'
        run: yarn test:run --output-style static

      # TODO: uncomment when repo is public
      # - uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #
      # - uses: codacy/codacy-coverage-reporter-action@v1
      #   with:
      #     api-token: ${{ secrets.CODACY_API_TOKEN }}
