name: '🔸 Run tests 🧪'

on:
  workflow_call:

jobs:
  test:
    name: 'Run unit tests'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}

      - uses: ./.github/actions/setup
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}

      - name: 'Run tests'
        run: yarn test:run --coverage

      - uses: codecov/codecov-action@v3

      - uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
