name: 'Deploy demo to GitHub Pages'

on:
  repository_dispatch:
    types: [ deploy-demo ]

  workflow_dispatch:

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/configure-pages@v3

      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./apps/demo/dist

      - uses: actions/deploy-pages@v1
