name: 'Run tests 🧪'

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: 'Run affected unit tests 🧪'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}

      - name: 'Run tests'
        run: nx affected --target=test:run --exclude=.
