name: 'Run tests 🧪'

on:
  pull_request:
    branches:
      - main
      - alpha
      - beta

  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - uses: myparcelnl/actions/bundlewatch@v3
        with:
          token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
