name: 'Run tests 🧪'

on:
  pull_request:
    branches:
      - main

  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: 'Run affected unit tests 🧪'
    runs-on: ubuntu-22.04
    steps:
      - uses: myparcelnl/actions/setup-git-credentials@v3
        id: credentials
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v3
        with:
          token: ${{ steps.credentials.outputs.token }}

      - uses: ./.github/actions/setup
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}

      - uses: myparcelnl/actions/bundlewatch@v3
        with:
          token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}

      - name: 'Run tests'
        run: |
          yarn nx affected \
            --target=test:run \
            --parallel \
            --output-style=static
