name: 'Run tests 🧪'

on:
  pull_request:
    branches:
      - main

  workflow_call:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: myparcelnl/actions/yarn2-install@v2
        with:
          yarn-args: --no-immutable

      - run: yarn test

      - uses: myparcelnl/actions/update-coverage@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
