name: 'Run tests 🧪'

on:
  pull_request:
    branches:
      - main

  workflow_call:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: myparcelnl/actions/yarn-install@v4

#      - run: yarn test # there are no tests yet so you don’t have to run

      - uses: myparcelnl/actions/update-coverage@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
