name: '🔸 Run tests 🧪'

on:
  workflow_call:

jobs:
  test:
    name: 'Run unit tests'
    runs-on: ubuntu-arm
    strategy:
      matrix:
        node-version: [18, 'current']
    steps:
      - uses: actions/checkout@v4

      - uses: myparcelnl/actions/yarn-install@v4
        if: matrix.node-version == 'current'

      - uses: myparcelnl/actions/yarn-install@v4
        if: matrix.node-version != 'current'
        with:
          node-version: ${{ matrix.node-version }}

      - uses: ./.github/actions/build

      - uses: myparcelnl/actions/nx-run-many@v4
        with:
          target: 'test:coverage'
          args: '--runner=cloud --parallel=false'

      - name: 'Move coverage files'
        if: matrix.node-version == 'current'
        shell: bash
        #language=bash
        run: |
          yarn workspaces foreach -Apv \
            --exclude=. \
            exec \
            bash -c 'if [ -f coverage/clover.xml ]; then mv coverage/clover.xml coverage/${npm_package_name//\//-}.xml; fi' -- {}

          mkdir -p ./coverage
          cp ./apps/*/coverage/*.xml ./coverage/ || true
          cp ./libs/*/coverage/*.xml ./coverage/ || true

      - uses: codecov/codecov-action@v3
        if: matrix.node-version == 'current'
        with:
          files: coverage/*.xml
          flags: unit
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    runs-on: ubuntu-arm
    steps:
      - uses: actions/checkout@v4

      - uses: myparcelnl/actions/yarn-install@v4

      - uses: ./.github/actions/build

      - uses: myparcelnl/actions/bundlewatch@v4
        with:
          token: ${{ secrets.BUNDLEWATCH_TOKEN }}
