name: '🔸 Run tests 🧪'

on:
  workflow_call:

jobs:
  test:
    name: 'Run unit tests'
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: ['18', 'current']
    steps:
      - uses: actions/checkout@v4

      - uses: myparcelnl/actions/yarn-install@v4
        if: matrix.node-version == 'current'

      - uses: myparcelnl/actions/yarn-install@v4
        if: matrix.node-version != 'current'
        with:
          node-version: ${{ matrix.node-version }}

      - uses: ./.github/actions/build

      - uses: myparcelnl/actions/nx-run-many@v4
        with:
          target: 'test:coverage'
          parallel: '1'
          cloud: 'true'
          runner: 'cloud'

      - uses: myparcelnl/actions/collect-test-results@v4

      - uses: myparcelnl/actions/codecov-coverage@v4
        if: matrix.node-version == 'current'
        with:
          files: coverage/*.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - uses: myparcelnl/actions/codecov-test-results@v4
        if: matrix.node-version == 'current'
        with:
          files: junit/*.xml
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: myparcelnl/actions/yarn-install@v4

      - uses: ./.github/actions/build

      - uses: myparcelnl/actions/bundlewatch@v4
        with:
          token: ${{ secrets.BUNDLEWATCH_TOKEN }}
