name: '🔸 Run tests 🧪'

on:
  workflow_call:

jobs:
  test:
    name: 'Run unit tests'
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [18, 'current']
    steps:
      - uses: actions/checkout@v4

      - name: 'Handle coverage cache'
        uses: actions/cache@v3
        id: coverage-cache
        with:
          path: coverage/clover.xml
          key: coverage-${{ matrix.node-version }}-${{ hashFiles('package.json', 'yarn.lock', 'tsconfig.json', 'src/**/*', 'test/**/*') }}

      - uses: myparcelnl/actions/yarn-install@v4
        if: matrix.node-version == 'current' && steps.coverage-cache.outputs.cache-hit != 'true'

      - uses: myparcelnl/actions/yarn-install@v4
        if: matrix.node-version != 'current' && steps.coverage-cache.outputs.cache-hit != 'true'
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Run tests'
        if: steps.coverage-cache.outputs.cache-hit != 'true'
        #language=sh
        run: |
          yarn nx run-many \
            --target=test:coverage \
            --parallel=false \
            --output-style=static

      - uses: codecov/codecov-action@v3
        if: matrix.node-version == 'current'
        with:
          files: coverage/clover.xml
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: myparcelnl/actions/yarn-install@v4

      - uses: ./.github/actions/build

      - uses: myparcelnl/actions/bundlewatch@v4
        with:
          token: ${{ secrets.BUNDLEWATCH_TOKEN }}
